name: 'Build Publish Chainlink'

on:
  push:
    branches:
      - 'release/**'

jobs:

  build-publish-chainlink:
    # buildjet-2vcpu-ubuntu-1804
    runs-on: ubuntu-latest
    environment: build-publish
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: 'Docker build'
        run: |
          DOCKER_TAG=gha BUILDER="${AWS_ECR_URL}/builder" make docker

      - name: 'Docker build non-root'
        run: |
          DOCKER_TAG=gha-nonroot CHAINLINK_USER=chainlink make docker

      - name: 'Docker push, if applicable'
        run: |
          tools/ci/push_chainlink "$GITHUB_REF" "$GITHUB_REF_NAME" "$GITHUB_SHA"
